id: IABAB1E9E
ocr_import_info:
  bdrc_scan_id: W1KG17193
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-09-12 14:05:36.243500
last_modified: 2023-02-01 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17193
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17193
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་ས་སྐྱའི་ཕྱག་སྲོལ་རྒྱུན་མཁོའི་ཆོས་སྤྱོད་ཀྱི་རིམ་པ་ངོ་མཚར་མེ་ཏོག་འཕྲེང་བ།
  languages:
  - bo
bases:
  I1KG17553:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17553
      total_pages: 206
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG17553.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
